apiVersion: batch/v1
kind: Job
metadata:
  name: devopardy-alembic-migrate
  namespace: default
spec:
  template:
    metadata:
      name: devopardy-alembic-migrate
    spec:
      containers:
        - name: alembic
          image: devopswithbrian/devopardy-db-migration:0.14.0
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: DB_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: DATABASE_URL
            - name: DB_NAME
              value: devopardy
            - name: DB_HOST
              value: devopardy-db
            - name: ALEMBIC_CONFIG
              value: /usr/src/app/alembic.ini
          imagePullPolicy: Always
      restartPolicy: Never
