version: '3.8'

services:

  api:
    build: ./api
    #command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8004:80
    environment:
      - DATABASE_URL
    depends_on:
      - db

  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB