version: '3.8'

services:

  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
      - SECRET_KEY
    depends_on:
      - db

  db:
    image: postgres:15.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB