apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopardy-api
spec:
  selector:
    matchLabels:
      app: devopardy-api
  replicas: 1
  template:
    metadata:
      labels:
        app: devopardy-api
    spec:
      containers:
      - name: devopardy-api
        image: your-docker-username/devopardy-api:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: devopardy-prd
                key: DATABASE_URL
        volumeMounts:
        - name: devopardy-api-postgresql-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: devopardy-api-postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: devopardy-api-postgresql-persistent-volume-claim
      initContainers:
      - name: devopardy-api-db-migration
        image: devopswithbrian/devopardy-db-migration:latest
        env:
        - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: devopardy-prd
                key: DATABASE_URL