apiVersion: batch/v1
kind: Job
metadata:
  name: devopardy-alembic-migrate
  namespace: default
spec:
  template:
    metadata:
      name: devopardy-alembic-migrate
    spec:
      containers:
        - name: alembic
          image: devopswithbrian/devopardy-db-migration:1.1
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: DB_PASSWORD
            - name: DB_NAME
              value: devopardy
            - name: DB_HOST
              value: devopardy-db
            - name: ALEMBIC_CONFIG
              value: /app/alembic.ini
          imagePullPolicy: Always
      restartPolicy: Never
