apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopardy-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: devopardy-api
  replicas: 1
  template:
    metadata:
      labels:
        app: devopardy-api
    spec:
      containers:
        - name: devopardy-api
          image: devopswithbrian/devopardy-api:0.18.2
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: DB_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: SECRET_KEY
            - name: ADMIN_API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: ADMIN_API_USERNAME
            - name: ADMIN_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devopardy-prd
                  key: ADMIN_API_PASSWORD
            - name: DB_NAME
              value: devopardy
            - name: DB_HOST
              value: devopardy-db
          ports:
            - containerPort: 8000
              name: devopardy-api
